Repository pulumi/pulumi-yaml, pull requests merged in 2022-06, with the labels that each got.

#239 Special errors for an empty schema
  go.mod
  go.sum
  pkg/pulumiyaml/packages.go
Labels: impact/no-changelog-required

#243 Deterministic analyzer errors
  pkg/pulumiyaml/analyser.go
Labels: impact/no-changelog-required, area/expr

#230 [exec] Consume PackageReferences
  pkg/pulumiyaml/codegen/convert.go
  pkg/pulumiyaml/codegen/eject.go
  pkg/pulumiyaml/codegen/gen_program_test.go
  pkg/pulumiyaml/packages.go
  pkg/tests/example_transpile_test.go
Labels: impact/no-changelog-required

#245 Document Fn::ToBase64
  README.md
Labels: impact/no-changelog-required, area/docs

#257 Require fmt.Stringer for a Node
  pkg/pulumiyaml/syntax/nodes.go
  pkg/pulumiyaml/syntax/syntax_test.go
Labels: impact/no-changelog-required

#259 Add Fn::ToJSON to README
  README.md
Labels: impact/no-changelog-required

#262 Support converting invokes with no arguments
  pkg/pulumiyaml/codegen/eject.go
  pkg/pulumiyaml/codegen/load.go
  pkg/pulumiyaml/codegen/load_test.go
Labels: impact/no-changelog-required

#260 Support converting Fn::Secret to other languages
  examples/azure-app-service/Pulumi.yaml
  examples/azure-container-apps/Pulumi.yaml
  pkg/pulumiyaml/codegen/load.go
  pkg/tests/transpiled_examples/azure-app-service/nodejs/index.ts
  pkg/tests/transpiled_examples/azure-app-service/program.pp
  pkg/tests/transpiled_examples/azure-container-apps/program.pp
Labels: impact/no-changelog-required
