Repository pulumi/pulumi-yaml, pull requests merged in 2022-05, with the labels that each got.

#189 Cleanup token resolution
  pkg/pulumiyaml/README.md
  pkg/pulumiyaml/packages.go
Labels: impact/no-changelog-required

#205 Add Apache 2 license
  LICENSE
Labels: impact/no-changelog-required

#203 Add *good* error messages for extra fields on resources.
  CHANGELOG_PENDING.md
  pkg/pulumiyaml/analyser.go
  pkg/pulumiyaml/diags/diags.go
  pkg/pulumiyaml/diags/utils.go
  pkg/pulumiyaml/run_test.go
Labels: area/ux

#209 Correct minor typo in README
  README.md
Labels: impact/no-changelog-required

#207 De-duplicate errors
  CHANGELOG_PENDING.md
  pkg/pulumiyaml/analyser.go
  pkg/pulumiyaml/codegen/convert.go
  pkg/pulumiyaml/codegen/eject.go
  pkg/pulumiyaml/run.go
  pkg/pulumiyaml/run_async_diags_test.go
  pkg/pulumiyaml/sort_test.go
  pkg/pulumiyaml/syntax/diags.go
  pkg/server/server.go
  pkg/tests/example_transpile_test.go
Labels: area/ux

#195 Enable using awsx provider, other providers with shallow plain resource properties
  CHANGELOG_PENDING.md
  Makefile
  examples/aws-static-website/README.md
  examples/awsx-fargate/Pulumi.yaml
  examples/awsx-fargate/README.md
  go.mod
  go.sum
  pkg/pulumiyaml/codegen/eject.go
  pkg/pulumiyaml/codegen/gen_program_test.go
  pkg/pulumiyaml/packages.go
  pkg/pulumiyaml/run.go
  pkg/pulumiyaml/run_plugin_version_test.go
  pkg/pulumiyaml/sort.go
  pkg/pulumiyaml/sort_test.go
  pkg/tests/example_test.go
  pkg/tests/example_transpile_test.go
  pkg/tests/transpiled_examples/.gitignore
  pkg/tests/transpiled_examples/awsx-fargate/dotnet/MyStack.cs
  pkg/tests/transpiled_examples/awsx-fargate/go/main.go
  pkg/tests/transpiled_examples/awsx-fargate/nodejs/index.ts
  pkg/tests/transpiled_examples/awsx-fargate/program.pp
  pkg/tests/transpiled_examples/awsx-fargate/python/__main__.py
  pkg/tests/transpiled_examples/pulumi-variable/pulumi-variable/__main__.py
  scripts/get_schemas.sh
Labels: area/expr

#218 support Fn::FromBase64
  CHANGELOG_PENDING.md
  README.md
  pkg/pulumiyaml/ast/expr.go
  pkg/pulumiyaml/codegen/load.go
  pkg/pulumiyaml/run.go
  pkg/pulumiyaml/run_test.go
Labels: area/expr

#236 [sec] Update yaml to mitigate CVE-2022-28948
  go.mod
  go.sum
Labels: kind/engineering, security, impact/no-changelog-required

#217 feature: Fn::ReadFile to read file from disk, support Stack README functionality
  CHANGELOG_PENDING.md
  README.md
  examples/readme/Pulumi.README.md
  examples/readme/Pulumi.yaml
  pkg/pulumiyaml/ast/expr.go
  pkg/pulumiyaml/codegen/load.go
  pkg/pulumiyaml/run.go
  pkg/pulumiyaml/run_test.go
  pkg/tests/example_transpile_test.go
  pkg/tests/transpiled_examples/readme/go/main.go
  pkg/tests/transpiled_examples/readme/nodejs/index.ts
  pkg/tests/transpiled_examples/readme/program.pp
  pkg/tests/transpiled_examples/readme/python/__main__.py
Labels: area/expr

#231 Remove mutexes introduced due to concurrency bug
  go.mod
  go.sum
  pkg/pulumiyaml/codegen/gen_program_test.go
  pkg/pulumiyaml/packages.go
  pkg/tests/example_transpile_test.go
Labels: impact/no-changelog-required
